# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de3746159f1773eb9ff8c77a1a6d82c82e5c28a547c468d76fb1784470ba22f3fc9d369a53e6804ec557588fc1471d556a0140ded7282eb31f4a8862d61664d3

test:
  secret_key_base: 85d79500b1856e6322ee9987e32475ff8daa793df8fc26498241a00155127a5681987fc6b2eeed9269cd1c544f27cc59537893a5502f941e6c16fa6ec051fff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
